#pragma once

const int ENTER_KEY = 13, ESC_KEY = 27, CTRL_C_KEY = 3, BACKSPACE_KEY = 8;

const int SPEC_KEY_PREFIX = 224;
const int SPEC_KEY_DEL = SPEC_KEY_PREFIX << 8 | 83,
	SPEC_KEY_UP = SPEC_KEY_PREFIX << 8 | 72,
	SPEC_KEY_DOWN = SPEC_KEY_PREFIX << 8 | 80,
	SPEC_KEY_LEFT = SPEC_KEY_PREFIX << 8 | 75,
	SPEC_KEY_RIGHT = SPEC_KEY_PREFIX << 8 | 77;